language: php
php:
  - 7.0
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE homestead;'
install:
  - "composer install"
script:
  - "mv ./.env.example ./.env"
  - "php artisan migrate --seed"
  - "vendor/bin/phpunit"